version: "3.7"

services:
  mariadb:
    image: mariadb:10.2.38
    ports:
      - 3306:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MARIADB_ROOT_PASSWORD: root123

  ticket-backend:
    depends_on:
    - mariadb
    image: roandocker/ticket-manager:0.0.1
    command: sh -c "./ticker-backend; tail -f /dev/null"
    ports:
      - 8080:8080
    environment:
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWD: root123
      DB_DATABASE: ticket
      DB_LOGMODE: "true"


volumes:
  todo-mysql-data: