# default db host
DB_HOST: '127.0.0.1'
# default db port
DB_PORT: '3306'
# default db name
DB_USER: 'root'
# default MYSQL name
DB_PASSWD: 'root123'
# default db name
DB_DATABASE: 'ticket'
# MYSQL log
DB_LOGMODE: false
# debug mode
DebugMode: true
# Log Level
LogLevel: 'debug'
# Default Page Size
PAGE_SIZE: 10