version: "3.7"

services:
  mariadb:
    image: mariadb:10.2.38
    ports:
      - 3306:3306
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MARIADB_ROOT_PASSWORD: root123
    restart: on-failure

  initdata-job:
    depends_on:
    - mariadb
    image: roandocker/initdata-job:latest
    environment: 
      MARIADB_SERVICE_HOST: "mariadb"
      SQL_FILE: "istioAlltime"
      GIT_BRANCH: "master"
      GITURL: "github.com/codeandcode0x/istioAlltime.git"
      GITUSER: ""
      GITPASSWD: ""
      MIGRATION: "MARIADB_SERVICE_HOST"
      DBUSER: "root"
      DBPASSWD: "root123"
      INTERVAL_TIME: "5"
    restart: on-failure

  ticket-manager:
    depends_on:
    - initdata-job
    image: roandocker/ticket-manager:latest
    command: /bin/sh -c "./ticket-manager"
    ports:
      - 8080:8080
    environment:
      DB_HOST: mariadb
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWD: root123
      DB_DATABASE: ticket
      DB_LOGMODE: "true"
    restart: always

  ticket-fronted:
    depends_on:
    - initdata-job
    - ticket-manager
    image: roandocker/ticket-frontend:latest
    command: /bin/sh -c "java -jar /root/ticket-frontend.jar"
    ports:
      - 8090:8090
    environment:
      DB_HOST: mariadb
      TICKET_MANAGER_HOST: ticket-manager:8080
    restart: always


volumes:
  todo-mysql-data: